### ISSUE TITLE
Weather Script

### ISSUE THREAD

**Issue by legman** [sos-tactical-gaming/SpecialOperations2#13]
Simple script that allows the admin to change weather and time the mission starts on with mission params.

By default these should be pseudo random to make sure each mission is completely different. It should choose out of a list of preset times that are interesting and avoid times such as 00:00 which would be pitch black.

The folder should be called  **environment** and the functions should be discussed.

**Comment by Catshannon** [comment]
done scrub

**Comment by JohanLanges** [comment]
Let's keep it clean guys!

**Comment by legman** [comment]
Closing as cat only has to make tiny changes!
