### ISSUE TITLE
Add towing to vehicles

### ISSUE THREAD

**Issue by JohanLanges** [sos-tactical-gaming/SpecialOperations2#14]
An idea from Catshannon to add an action to tow vehicles using the rope system. It's always frustrating when a perfectly usable vehicle is stuck in a ditch, and there is no way to get it out. The towing script should be used in those situations. Another situation could be when one of the vehicles is damaged and need to be towed to get it out of enemy fire.

Pseudo code:
Using "ropeCreate" and "getNearest" we can attach a rope between two vehicles. With the utility class SOS_VehicleTypes, we can define Towing vehicles with the attaching points. So each vehicle will have a different attaching point on its body to so that the rope will be attached correctly. 

The action will only be available to the driver in the towing vehicle and when the vehicle is not moving. When the action is called, it will check any vehicle in the area that can be towed. Checked if that vehicle isn't moving above a certain speed (could be spassing out) and if it's in range (attach rope point beginning - attach rope point end <= rope length).

Some problems that could arise:
- Rope could be buggy as hell (probably is)
- Might damage both vehicles (or one of them)
- Mass could be a problem

Challenges
- How to determine if vehicle can be towed. (perhaps with the calculation: tow vehicle mass > other vehicle mass).
- Can you tow a towed vehicle (creating a line of vehicles)
- How to release the tow (The driver of each vehicle gets access to the action release rope?)

**Comment by legman** [comment]
I like the idea, but i has to be done well. You should have a 'Attach Tow to #VEHICLE' action when parked near a vehicle.

If a player is driving said vehicle they need to 'Allow Towing' in their action menu.

First thing is to test rope physics, if that is buggy with ground vehicles then i would say scrap the idea completely as doing it any other way would be inferior.

**Comment by JohanLanges** [comment]
Currently not possible without huge workarounds. The problem lies with the physx of vehicles not applying when vehicle is empty (so no driver or passenger). Besides that the update on the rope isn't good enough for multiplayer. Because of this the rope will expand and retract frequently causing rubber banding. This means that small vehicles will catapult really easy.

Possible workarounds:
- Setting the mass on vehicles to avoid catapulting
- Let the vehicle that is being towed float a bit in the air, so the ropes won't have to deal with the drag of the ground

This is currently to much work to get it right. As this was just an idea not integral to the mission, the issue can be closed.
