### ISSUE TITLE
Loading and Saving gear (Virtual Arsenal)

### ISSUE THREAD

**Issue by JohanLanges** [sos-tactical-gaming/SpecialOperations2#15]
The radio from Task Force Radio breaks the ability to load your gear from the virtual arsenal. To fix this, we need to tie into the save gear functionality and remove the radio on save. And add the radio on load.

**Comment by legman** [comment]
I don't actually think there is a decent way of doing this - ideally we need to hyjack the arsenal menu system which is out of scope of a script alone!

We should report an issue to Bohemia requesting that having an unkown item in your loadout shouldnt break the save.
