### ISSUE TITLE
Set solid AI difficulty

### ISSUE THREAD

**Issue by legman** [sos-tactical-gaming/SpecialOperations2#32]
Do through Description.ext

**Comment by legman** [comment]
https://community.bistudio.com/wiki/AI_Sub-skills

**Comment by legman** [comment]
https://community.bistudio.com/wiki/CfgAISkill

**Comment by legman** [comment]
lowish accuracy should mean more spray and pray from AI rather than well aimed headshots

**Comment by Catshannon** [comment]
Closed

**Comment by legman** [comment]
#41
