### ISSUE TITLE
Rearm action is sometimes not removed for fixed wing

### ISSUE THREAD

**Issue by legman** [sos-tactical-gaming/SpecialOperations2#54]
Hard to reproduce.

**Comment by rdbeerman** [comment]
This also happens in helicopters, action becomes available once landed.

**Comment by legman** [comment]
Ok cats gonna manage this differently and that should remove chance for error!

**Comment by Catshannon** [comment]
yee removing action on service (if an action calls the FNC) and adding it to the driver only not the vehicle.

**Comment by legman** [comment]
possibly fixed now - will reopen if new reports come up
