### ISSUE TITLE
CSAT vehicles are unlocked

### ISSUE THREAD

**Issue by legman** [sos-tactical-gaming/SpecialOperations2#63]
Means that douches can steal them.

**Comment by legman** [comment]
will write a function that iterates groups and locks vehicles

**Comment by legman** [comment]
**SOS_fnc_lockVehicles**

**Comment by Catshannon** [comment]
Leave unarmed Ifrits and Zamaks unlocked please.

**Comment by legman** [comment]
sounds fine by me

**Comment by legman** [comment]
**make sure you call this function for every vehicle you make and every group with a vehicle in it you make!**

**Comment by legman** [comment]
**SOS_fnc_lockSideVehicles**
**SOS_fnc_lockGroupVehicles**

**SOS_fnc_lockSideVehicles** will be called when the mission is generated - then future calls to **SOS_fnc_lockGroupVehicles** will be made when reinforcements are added!
