### ISSUE TITLE
Add paradrop to all transport helicopters

### ISSUE THREAD

**Issue by JohanLanges** [sos-tactical-gaming/SpecialOperations2#9]
When players eject from a flying helicopter, a parachute should be opened at a certain height (100, 150 meters above ground), without removing the backpack.

When a transport helicopter spawns (Hummingbird, Ghost Hawk, etc), the eject action should be overridden by our script. It will kick out the player and when it reaches the given altitude a parachute will spawn and load in the player. If the player ejects below the given altitude, he/she will fall to the ground like normal.

I found this script we can use for inspiration: http://www.armaholic.com/page.php?id=25458.

**Comment by legman** [comment]
Good work
